spring:
  profiles:
    active: dev

## 自己使用时，将上面的配置删掉。
ming:
  tools:
    baidu:
      access-ocr-key: Your 百度OCR accessKey
      secret-ocr-key: Your 百度OCR secretKey
      access-trans-key: Your 百度翻译 accessKey
      secret-trans-key: Your 百度翻译 secretKey
    qiniu:
      access-key: Your 七牛云 accessKey
      secret-key: Your 七牛云 secretKey
      bucket-name: 要上传到的空间
      file-path-prefix: 文件地址前缀，cdn地址
